### ISSUE TITLE
mac配置环境

### ISSUE THREAD

**Issue by zszen** [whosydd/typora-open#1]
`alias typora="open -a typora"` 放到 `~/.zprofile` 可以使用，放到 `~/.bash_profile` 没有效果

macos 11.2.3

**Comment by whosydd** [comment]
`.bash_profile`是针对`bash`的配置文件，如果你已经在该文件中添加别名，建议你切换到`bash`环境，运行`typora xxx.md`命令查看是否能够打开md文件，很抱歉我现在没有macOS设备，没法进一步测试
