### ISSUE TITLE
你好，我设置了系统变量，但是仍然打不开 typora

### ISSUE THREAD

**Issue by Pupper0601** [whosydd/typora-open#2]

**Comment by whosydd** [comment]
这个插件的原理是通过命令行工具打开typora，你可以参考[这里](https://support.typora.io/Use-Typora-From-Shell-or-cmd/)进行配置，然后使用终端执行`typora`命令，看是否可以打开typora，如果无法正常打开typora，请说明你使用的系统环境，以及相应的报错信息
